version: "3.9"
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: diego_igor
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: base_dados
    networks:
      - rede-web-bridge
    volumes:
      - meu-volume-web:/home/arquivos
  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - database
    networks:
      - rede-web-bridge
    volumes:
      - meu-volume-web:/home/arquivos

networks:
    rede-web-bridge:
        driver: bridge
volumes:
  meu-volume-web:
    
